#include "editor/LanguageSupport.h"
#include <QFileInfo>
#include <QHash>

namespace litecode::editor {
namespace {

[[maybe_unused]] QByteArray lexillaFallbackForLanguage(const QString& id) {
    static const QHash<QString, QByteArray> lexers{
        {QStringLiteral("bat"), QByteArrayLiteral("batch")},
        {QStringLiteral("clojure"), QByteArrayLiteral("lisp")},
        {QStringLiteral("coffeescript"), QByteArrayLiteral("coffeescript")},
        {QStringLiteral("c"), QByteArrayLiteral("cpp")},
        {QStringLiteral("cpp"), QByteArrayLiteral("cpp")},
        {QStringLiteral("cuda-cpp"), QByteArrayLiteral("cpp")},
        {QStringLiteral("csharp"), QByteArrayLiteral("cpp")},
        {QStringLiteral("css"), QByteArrayLiteral("css")},
        {QStringLiteral("dart"), QByteArrayLiteral("dart")},
        {QStringLiteral("diff"), QByteArrayLiteral("diff")},
        {QStringLiteral("dockerfile"), QByteArrayLiteral("bash")},
        {QStringLiteral("dotenv"), QByteArrayLiteral("props")},
        {QStringLiteral("fsharp"), QByteArrayLiteral("fsharp")},
        {QStringLiteral("git-commit"), QByteArrayLiteral("props")},
        {QStringLiteral("git-rebase"), QByteArrayLiteral("props")},
        {QStringLiteral("ignore"), QByteArrayLiteral("props")},
        {QStringLiteral("go"), QByteArrayLiteral("cpp")},
        // Lexilla has no separate Groovy lexer. Its C-family lexer is the
        // upstream-supported lexical fallback for Groovy's Java-like syntax.
        {QStringLiteral("groovy"), QByteArrayLiteral("cpp")},
        {QStringLiteral("handlebars"), QByteArrayLiteral("hypertext")},
        {QStringLiteral("hlsl"), QByteArrayLiteral("cpp")},
        {QStringLiteral("html"), QByteArrayLiteral("hypertext")},
        {QStringLiteral("ini"), QByteArrayLiteral("props")},
        {QStringLiteral("properties"), QByteArrayLiteral("props")},
        {QStringLiteral("java"), QByteArrayLiteral("cpp")},
        {QStringLiteral("javascript"), QByteArrayLiteral("cpp")},
        {QStringLiteral("javascriptreact"), QByteArrayLiteral("cpp")},
        {QStringLiteral("jsx-tags"), QByteArrayLiteral("cpp")},
        {QStringLiteral("json"), QByteArrayLiteral("json")},
        {QStringLiteral("jsonc"), QByteArrayLiteral("json")},
        {QStringLiteral("jsonl"), QByteArrayLiteral("json")},
        {QStringLiteral("snippets"), QByteArrayLiteral("json")},
        {QStringLiteral("julia"), QByteArrayLiteral("julia")},
        {QStringLiteral("juliamarkdown"), QByteArrayLiteral("markdown")},
        {QStringLiteral("tex"), QByteArrayLiteral("latex")},
        {QStringLiteral("latex"), QByteArrayLiteral("latex")},
        {QStringLiteral("bibtex"), QByteArrayLiteral("bib")},
        {QStringLiteral("less"), QByteArrayLiteral("css")},
        {QStringLiteral("lua"), QByteArrayLiteral("lua")},
        {QStringLiteral("makefile"), QByteArrayLiteral("makefile")},
        {QStringLiteral("markdown"), QByteArrayLiteral("markdown")},
        {QStringLiteral("markdown-math"), QByteArrayLiteral("markdown")},
        {QStringLiteral("objective-c"), QByteArrayLiteral("cpp")},
        {QStringLiteral("objective-cpp"), QByteArrayLiteral("cpp")},
        {QStringLiteral("perl"), QByteArrayLiteral("perl")},
        {QStringLiteral("raku"), QByteArrayLiteral("perl")},
        {QStringLiteral("php"), QByteArrayLiteral("hypertext")},
        {QStringLiteral("powershell"), QByteArrayLiteral("powershell")},
        {QStringLiteral("prompt"), QByteArrayLiteral("markdown")},
        {QStringLiteral("instructions"), QByteArrayLiteral("markdown")},
        {QStringLiteral("skill"), QByteArrayLiteral("markdown")},
        {QStringLiteral("jade"), QByteArrayLiteral("hypertext")},
        {QStringLiteral("python"), QByteArrayLiteral("python")},
        {QStringLiteral("r"), QByteArrayLiteral("r")},
        {QStringLiteral("razor"), QByteArrayLiteral("hypertext")},
        {QStringLiteral("ruby"), QByteArrayLiteral("ruby")},
        {QStringLiteral("rust"), QByteArrayLiteral("rust")},
        {QStringLiteral("scss"), QByteArrayLiteral("css")},
        {QStringLiteral("shaderlab"), QByteArrayLiteral("cpp")},
        {QStringLiteral("shellscript"), QByteArrayLiteral("bash")},
        {QStringLiteral("sql"), QByteArrayLiteral("sql")},
        {QStringLiteral("swift"), QByteArrayLiteral("cpp")},
        {QStringLiteral("typescript"), QByteArrayLiteral("cpp")},
        {QStringLiteral("typescriptreact"), QByteArrayLiteral("cpp")},
        {QStringLiteral("vb"), QByteArrayLiteral("vb")},
        {QStringLiteral("xml"), QByteArrayLiteral("xml")},
        {QStringLiteral("xsl"), QByteArrayLiteral("xml")},
        {QStringLiteral("yaml"), QByteArrayLiteral("yaml")},
        {QStringLiteral("dockercompose"), QByteArrayLiteral("yaml")},
    };
    return lexers.value(id);
}

} // namespace

LanguageSupport languageSupportForFile(const QString& filePath) {
    const QFileInfo info(filePath);
    const QString name = info.fileName().toLower();
    if (name == QStringLiteral("cmakelists.txt"))
        return {QStringLiteral("cmake"), QByteArrayLiteral("cmake")};

    if (name == QStringLiteral("dockerfile"))
        return {QStringLiteral("dockerfile"), QByteArrayLiteral("bash")};
    if (name == QStringLiteral("makefile") || name == QStringLiteral("gnumakefile"))
        return {QStringLiteral("makefile"), QByteArrayLiteral("makefile")};
    if (name == QStringLiteral("rakefile") || name == QStringLiteral("gemfile"))
        return {QStringLiteral("ruby"), QByteArrayLiteral("ruby")};
    if (name == QStringLiteral("meson.build") || name == QStringLiteral("workspace"))
        return {QStringLiteral("python"), QByteArrayLiteral("python")};
    if (name == QStringLiteral(".env") || name.startsWith(QStringLiteral(".env.")))
        return {QStringLiteral("properties"), QByteArrayLiteral("props")};
    if (name == QStringLiteral(".gitignore") || name == QStringLiteral(".gitattributes") ||
        name == QStringLiteral(".gitmodules"))
        return {QStringLiteral("ignore"), QByteArrayLiteral("props")};

    static const QHash<QString, LanguageSupport> languages{
        {QStringLiteral("c"), {QStringLiteral("c"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cc"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cpp"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cxx"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("h"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("hpp"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("hh"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("hxx"), {QStringLiteral("cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("m"), {QStringLiteral("objective-c"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("mm"), {QStringLiteral("objective-cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cu"), {QStringLiteral("cuda-cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cuh"), {QStringLiteral("cuda-cpp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("kt"), {QStringLiteral("kotlin"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("kts"), {QStringLiteral("kotlin"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("scala"), {QStringLiteral("scala"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("swift"), {QStringLiteral("swift"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("glsl"), {QStringLiteral("glsl"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("vert"), {QStringLiteral("glsl"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("frag"), {QStringLiteral("glsl"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("hlsl"), {QStringLiteral("hlsl"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("py"), {QStringLiteral("python"), QByteArrayLiteral("python")}},
        {QStringLiteral("pyw"), {QStringLiteral("python"), QByteArrayLiteral("python")}},
        {QStringLiteral("js"), {QStringLiteral("javascript"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("mjs"), {QStringLiteral("javascript"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cjs"), {QStringLiteral("javascript"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("jsx"), {QStringLiteral("javascriptreact"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("ts"), {QStringLiteral("typescript"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("tsx"), {QStringLiteral("typescriptreact"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("java"), {QStringLiteral("java"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("cs"), {QStringLiteral("csharp"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("go"), {QStringLiteral("go"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("json"), {QStringLiteral("json"), QByteArrayLiteral("json")}},
        {QStringLiteral("jsonc"), {QStringLiteral("jsonc"), QByteArrayLiteral("json")}},
        {QStringLiteral("jsonl"), {QStringLiteral("json"), QByteArrayLiteral("json")}},
        {QStringLiteral("html"), {QStringLiteral("html"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("htm"), {QStringLiteral("html"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("vue"), {QStringLiteral("vue"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("svelte"), {QStringLiteral("svelte"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("astro"), {QStringLiteral("astro"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("php"), {QStringLiteral("php"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("phtml"), {QStringLiteral("php"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("cshtml"), {QStringLiteral("razor"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("xml"), {QStringLiteral("xml"), QByteArrayLiteral("hypertext")}},
        {QStringLiteral("xsd"), {QStringLiteral("xml"), QByteArrayLiteral("xml")}},
        {QStringLiteral("xsl"), {QStringLiteral("xml"), QByteArrayLiteral("xml")}},
        {QStringLiteral("svg"), {QStringLiteral("xml"), QByteArrayLiteral("xml")}},
        {QStringLiteral("css"), {QStringLiteral("css"), QByteArrayLiteral("css")}},
        {QStringLiteral("scss"), {QStringLiteral("scss"), QByteArrayLiteral("css")}},
        {QStringLiteral("sass"), {QStringLiteral("scss"), QByteArrayLiteral("css")}},
        {QStringLiteral("less"), {QStringLiteral("less"), QByteArrayLiteral("css")}},
        {QStringLiteral("md"), {QStringLiteral("markdown"), QByteArrayLiteral("markdown"), true}},
        {QStringLiteral("markdown"),
         {QStringLiteral("markdown"), QByteArrayLiteral("markdown"), true}},
        {QStringLiteral("ron"), {QStringLiteral("markdown"), QByteArrayLiteral("markdown"), true}},
        {QStringLiteral("workbook"),
         {QStringLiteral("markdown"), QByteArrayLiteral("markdown"), true}},
        {QStringLiteral("mdx"), {QStringLiteral("markdown"), QByteArrayLiteral("markdown"), true}},
        {QStringLiteral("adoc"), {QStringLiteral("asciidoc"), QByteArrayLiteral("asciidoc")}},
        {QStringLiteral("asciidoc"), {QStringLiteral("asciidoc"), QByteArrayLiteral("asciidoc")}},
        {QStringLiteral("mmd"), {QStringLiteral("mermaid"), QByteArrayLiteral("markdown")}},
        {QStringLiteral("mermaid"), {QStringLiteral("mermaid"), QByteArrayLiteral("markdown")}},
        {QStringLiteral("tex"), {QStringLiteral("latex"), QByteArrayLiteral("latex")}},
        {QStringLiteral("sty"), {QStringLiteral("latex"), QByteArrayLiteral("latex")}},
        {QStringLiteral("cls"), {QStringLiteral("latex"), QByteArrayLiteral("latex")}},
        {QStringLiteral("bib"), {QStringLiteral("bibtex"), QByteArrayLiteral("bib")}},
        {QStringLiteral("sh"), {QStringLiteral("shellscript"), QByteArrayLiteral("bash")}},
        {QStringLiteral("bash"), {QStringLiteral("shellscript"), QByteArrayLiteral("bash")}},
        {QStringLiteral("zsh"), {QStringLiteral("shellscript"), QByteArrayLiteral("bash")}},
        {QStringLiteral("fish"), {QStringLiteral("shellscript"), QByteArrayLiteral("bash")}},
        {QStringLiteral("bat"), {QStringLiteral("bat"), QByteArrayLiteral("batch")}},
        {QStringLiteral("cmd"), {QStringLiteral("bat"), QByteArrayLiteral("batch")}},
        {QStringLiteral("ps1"), {QStringLiteral("powershell"), QByteArrayLiteral("powershell")}},
        {QStringLiteral("psm1"), {QStringLiteral("powershell"), QByteArrayLiteral("powershell")}},
        {QStringLiteral("psd1"), {QStringLiteral("powershell"), QByteArrayLiteral("powershell")}},
        {QStringLiteral("yaml"), {QStringLiteral("yaml"), QByteArrayLiteral("yaml")}},
        {QStringLiteral("yml"), {QStringLiteral("yaml"), QByteArrayLiteral("yaml")}},
        {QStringLiteral("sql"), {QStringLiteral("sql"), QByteArrayLiteral("sql")}},
        {QStringLiteral("rs"), {QStringLiteral("rust"), QByteArrayLiteral("rust")}},
        {QStringLiteral("toml"), {QStringLiteral("toml"), QByteArrayLiteral("toml")}},
        {QStringLiteral("ini"), {QStringLiteral("ini"), QByteArrayLiteral("props")}},
        {QStringLiteral("cfg"), {QStringLiteral("ini"), QByteArrayLiteral("props")}},
        {QStringLiteral("properties"), {QStringLiteral("properties"), QByteArrayLiteral("props")}},
        {QStringLiteral("diff"), {QStringLiteral("diff"), QByteArrayLiteral("diff")}},
        {QStringLiteral("patch"), {QStringLiteral("diff"), QByteArrayLiteral("diff")}},
        {QStringLiteral("lua"), {QStringLiteral("lua"), QByteArrayLiteral("lua")}},
        {QStringLiteral("rb"), {QStringLiteral("ruby"), QByteArrayLiteral("ruby")}},
        {QStringLiteral("erb"), {QStringLiteral("ruby"), QByteArrayLiteral("ruby")}},
        {QStringLiteral("pl"), {QStringLiteral("perl"), QByteArrayLiteral("perl")}},
        {QStringLiteral("pm"), {QStringLiteral("perl"), QByteArrayLiteral("perl")}},
        {QStringLiteral("r"), {QStringLiteral("r"), QByteArrayLiteral("r")}},
        {QStringLiteral("dart"), {QStringLiteral("dart"), QByteArrayLiteral("dart")}},
        {QStringLiteral("fs"), {QStringLiteral("fsharp"), QByteArrayLiteral("fsharp")}},
        {QStringLiteral("fsx"), {QStringLiteral("fsharp"), QByteArrayLiteral("fsharp")}},
        {QStringLiteral("coffee"),
         {QStringLiteral("coffeescript"), QByteArrayLiteral("coffeescript")}},
        {QStringLiteral("asm"), {QStringLiteral("asm"), QByteArrayLiteral("asm")}},
        {QStringLiteral("s"), {QStringLiteral("asm"), QByteArrayLiteral("asm")}},
        {QStringLiteral("jl"), {QStringLiteral("julia"), QByteArrayLiteral("julia")}},
        {QStringLiteral("f"), {QStringLiteral("fortran"), QByteArrayLiteral("fortran")}},
        {QStringLiteral("f90"), {QStringLiteral("fortran"), QByteArrayLiteral("fortran")}},
        {QStringLiteral("f95"), {QStringLiteral("fortran"), QByteArrayLiteral("fortran")}},
        {QStringLiteral("hs"), {QStringLiteral("haskell"), QByteArrayLiteral("haskell")}},
        {QStringLiteral("lhs"), {QStringLiteral("haskell"), QByteArrayLiteral("literatehaskell")}},
        {QStringLiteral("lisp"), {QStringLiteral("lisp"), QByteArrayLiteral("lisp")}},
        {QStringLiteral("clj"), {QStringLiteral("clojure"), QByteArrayLiteral("lisp")}},
        {QStringLiteral("pas"), {QStringLiteral("pascal"), QByteArrayLiteral("pascal")}},
        {QStringLiteral("vb"), {QStringLiteral("vb"), QByteArrayLiteral("vb")}},
        {QStringLiteral("zig"), {QStringLiteral("zig"), QByteArrayLiteral("zig")}},
        {QStringLiteral("nim"), {QStringLiteral("nim"), QByteArrayLiteral("nim")}},
        {QStringLiteral("d"), {QStringLiteral("d"), QByteArrayLiteral("d")}},
        {QStringLiteral("tcl"), {QStringLiteral("tcl"), QByteArrayLiteral("tcl")}},
        {QStringLiteral("v"), {QStringLiteral("verilog"), QByteArrayLiteral("verilog")}},
        {QStringLiteral("sv"), {QStringLiteral("verilog"), QByteArrayLiteral("verilog")}},
        {QStringLiteral("vhd"), {QStringLiteral("vhdl"), QByteArrayLiteral("vhdl")}},
        {QStringLiteral("vhdl"), {QStringLiteral("vhdl"), QByteArrayLiteral("vhdl")}},
        {QStringLiteral("groovy"), {QStringLiteral("groovy"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("gradle"), {QStringLiteral("groovy"), QByteArrayLiteral("cpp")}},
        {QStringLiteral("ninja"), {QStringLiteral("makefile"), QByteArrayLiteral("makefile")}},
    };
    return languages.value(info.suffix().toLower());
}

} // namespace litecode::editor
